version: '3.6'

networks:
  net:
    driver: overlay

services:
  pjm:
    image: matjaz99/pjm:0.1.0-SNAPSHOT
    ports:
      - 8080:8080
    networks:
      - net
    environment:
      - TZ=${TZ}
      - PJM_PROJECTS_DIRECTORY=/opt/pjm/projects
    volumes:
      - /var/log:/opt/pjm/log
      - /opt/pjm/projects:/opt/pjm/projects
    deploy:
      mode: replicated
      replicas: 1
